itfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('profiles/', views.profiles, name="profiles"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),   
    path('profile/<str:username>/', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('create-skill/', views.createSkill, name="create-skill"),
    path('update-skill/<slug:skill_slug>/', views.updateSkill, name="update-skill"),
    path('delete-skill/<slug:skill_slug>/', views.deleteSkill, name="delete-skill"),
    path('skill/<slug:skill_slug>', views.profiles_by_skill, name="skill"),
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:username>/', views.createMessage, name="create-message"),

]

projects/models.py
from django.db import models
from users.models import Profile
import uuid
from django.utils.text import slugify

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name    


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField(null=True, blank=True, default="project_images/default.jpg", upload_to='project_images')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    total_votes = models.IntegerField(default=0, null=True, blank=True)
    votes_ratio = models.IntegerField(default=0, null=True, blank=True)
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    source_link = models.CharField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()
        queryset = self.review_set.all().values_list('owner__id', flat=True).count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = upVotes
        self.vote_ratio = queryset

        self.save()

    class Meta:
        ordering = ('-created',)


class Review(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = [['owner', 'project']]
        ordering = ('created', )

    def __str__(self):
        return self.body


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    liked_object = models.ForeignKey(Project, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'liked_object')

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save, post_delete

class Skill(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True)
    slug = models.SlugField()
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.EmailField(max_length=50, blank=True, null=True)
    username = models.CharField(max_length=50, blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    image = models.ImageField(
        null=True, blank=True, upload_to='profile_images', default="profile_images/default.jpg")
    skills = models.ManyToManyField(Skill, blank=True)
    github = models.CharField(max_length=100, blank=True, null=True)
    twitter = models.CharField(max_length=100, blank=True, null=True)
    linkedin = models.CharField(max_length=100, blank=True, null=True)
    youtube = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

    class Meta:
        ordering = ['created']



class Message(models.Model):
    sender = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Skill, Message


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username',
                  'city', 'bio', 'intro', 'image',
                  'github', 'linkedin', 'twitter',
                  'youtube', 'website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})




class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body']

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.dispatch.dispatcher import receiver
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from django.urls import conf
from .models import Profile, Skill, Message
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from .utils import paginateProfiles, searchProfiles, searchMessage
from django.db.models import Q


def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Такого пользователя нет в системе')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')

        else:
            messages.error(request, 'Неверное имя пользователя или пароль')

    return render(request, 'users/login.html')


def logoutUser(request):
    logout(request)
    messages.info(request, 'Вы вышли из учетной записи')
    return redirect('projects')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(request, 'Аккаунт успешно создан!')

            login(request, user)
            return redirect('edit-account')

        else:
            messages.success(
                request, 'Во время регистрации возникла ошибка')

    context = {'page': page, 'form': form}
    return render(request, 'users/register.html', context)


def profiles(request):
    profiles, search_query = searchProfiles(request)
    custom_range, profiles = paginateProfiles(request, profiles, 6)
    context = {'profiles': profiles, 'search_query': search_query,
               'custom_range': custom_range}
    return render(request, 'users/profiles.html', context)


def userProfile(request, username):
    profile = Profile.objects.get(username=username)
    myProfile = request.user.profile

    main_skills = profile.skills.all()[:2]
    extra_skills = profile.skills.all()[2:]

    context = {'profile': profile, 'main_skills': main_skills,
               "extra_skills": extra_skills, 'myProfile': myProfile}
    return render(request, 'users/userProfile.html', context)


def profiles_by_skill(request, skill_slug):
    skill = get_object_or_404(Skill, slug=skill_slug)
    profiles = Profile.objects.filter(skills__in=[skill])
    context = {
        "profiles": profiles
    }

    return render(request, "users/profiles.html", context)


@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile

    skills = profile.skills.all()
    projects = profile.project_set.all()

    context = {'profile': profile, 'skills': skills, 'projects': projects}
    return render(request, 'users/myProfile.html', context)


@login_required(login_url='login')
def editAccount(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()

            return redirect('account')

    context = {'form': form, 'profile': profile}
    return render(request, 'users/account_form.html', context)


@login_required(login_url='login')
def createSkill(request):
    profile = request.user.profile
    form = SkillForm()

    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill_slug = request.POST.get('slug')
            skill_description = request.POST.get('description')
            profile.skills.get_or_create(name=skill, slug=skill_slug, description=skill_description)
            messages.success(request, 'Навык добавлен')
            return redirect('account')

    context = {'form': form}
    return render(request, 'users/skill_form.html', context)


@login_required(login_url='login')
def updateSkill(request, skill_slug):
    profile = request.user.profile
    skill = profile.skills.get(slug=skill_slug)
    form = SkillForm(instance=skill)

    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():
            form.save()
            messages.success(request, 'Навык успешно обновлен')
            return redirect('account')

    context = {'form': form}
    return render(request, 'users/skill_form.html', context)


@login_required(login_url='login')
def deleteSkill(request, skill_slug):
    profile = request.user.profile
    skill = profile.skills.get(slug=skill_slug)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'Навык успешно удален')
        return redirect('account')

    context = {'object': skill}
    return render(request, 'delete_template.html', context)


@login_required(login_url='login')
def inbox(request):
    profile = request.user.profile
    messageRequestss = profile.messages.all()
    unreadCount = messageRequestss.filter(is_read=False).count()
    search_query = searchMessage(request)
    sender = request.user.profile

    message = messageRequestss.distinct().filter(
        Q(name__icontains=search_query) |
        Q(subject__icontains=search_query)
    )

    context = {'messageRequests': message, 'unreadCount': unreadCount, 'profile': profile,
               'sender': sender, 'search_query': search_query}
    return render(request, 'users/messages.html', context)


@login_required(login_url='login')
def viewMessage(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    sender = request.user.profile

    if message.is_read == False:
        message.is_read = True
        message.save()
    context = {'message': message, 'profile': profile, 'sender': sender}
    return render(request, 'users/mess.html', context)


def createMessage(request, username):
    recipient = Profile.objects.get(username=username)
    form = MessageForm()
    profile = request.user.profile
    messageRequests = profile.messages.all()
    unreadCount = messageRequests.filter(is_read=False).count()

    try:
        sender = request.user.profile
    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()

            messages.success(request, 'Your message was successfully sent!')
            return redirect('user-profile', username=recipient.username)

    context = {'recipient': recipient, 'form': form, 'unreadCount': unreadCount, 'profile': profile, 'sender': sender}
    return render(request, 'users/createMes.html', context)

users/templates/users/account_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/editAcc.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Edit Profile</title>
</head>
<body>
    <header>
        <a href="{% url 'projects' %}" class="logo">FOLIo</a>
            <a href="" class="text1">Для вас</a>
            <a href="" class="text2">Подписки</a>
            <a href="{% url 'inbox' %}" class="text3">Чаты</a>
            <a href="" class="text4">Вы сохранили</a>
            <a href="" class="text5">О нас</a>
            <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                <img class="profile" src="{{ profile.image.url }}" alt="profile">
            <nav class="menu" id="menu">
                <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                <a href="{% url 'account' %}">Профиль</a>
                <a href="{% url 'logout' %}">Выход</a>
            </nav>
            <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
            <script src="{% static 'js/mainPage.js' %}"></script>
    </header>
        <container>
            <div class="post-logo">
                <img class="post-logo-img" src="{% static 'img/изображение 10.png' %}" alt="post-logo-img">
            </div>
        </container>
        <container>
            <div class="block-prof">
                <form class="form" method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="avatar">
                        <img class="avatar-img" src="{{ profile.image.url }}">
                        <input class="input__file" type="file" name="image" accept="image/*" multiple>
                    </div>

                    <div class="nickname">{{ profile.name }}</div>

                    <div class="name">
                        <label for="formInput#text"></label>
                        <input class="namee" id="id_name" type="text" name="name"
                            placeholder="Имя" value="{{ profile.name }}" />
                    </div>

                    <div class="town">
                        <label for="formInput#text"></label>
                        <input class="townn" id="id_city" type="text" name="city"
                            placeholder="Город" />
                    </div>

                    <div class="opisanie">
                        <label for="formInput#text"></label>
                        <input class="opisaniee" id="id_bio" type="text" name="bio"
                            placeholder="Описание" value="{{ profile.bio }}" />
                    </div>

                    <div class="vdohnovenie">
                        <label for="formInput#text"></label>
                        <input class="vdohnoveniee" id="id_intro" type="text" name="intro"
                            placeholder="Вдохновляет" value="{{ profile.intro }}" />
                    </div>

                    <div class="achizment">
                        <input class="achizmentt" id="id_username" type="text" name="username"
                           placeholder="Логин" value="{{ profile.username }}" />
                    </div>

                    <div class="github">
                        <label for="formInput#text"></label>
                        <input class="githubb" id="id_github" type="text" name="github"
                            placeholder="Ваш GitHub" value="{{ profile.github }}" />
                    </div>

                    <div class="tg">
                        <label for="formInput#text"></label>
                        <input class="tgg" id="id_twitter" type="text" name="twitter"
                            placeholder="Telegram" value="{{ profile.twitter }}" />
                    </div>

                    <div class="ds">
                        <label for="formInput#text"></label>
                        <input class="dss" id="if_linkedin" type="text" name="linkedin"
                            placeholder="Discord" value="{{ profile.linkedin }}" />
                    </div>

                    <div class="email">
                        <label for="formInput#text"></label>
                        <input class="emaill" id="id_email" type="email" name="email"
                            placeholder="Почта" value="{{ profile.email }}"/>
                    </div>

                    <div class="password">
                        <label for="formInput#text"></label>
                        <input class="passwordd" id="formInput#text" type="password" name="password1"
                            placeholder="Введите пароль" />
                    </div>

                    <div class="repeat">
                        <label for="formInput#text"></label>
                        <input class="repeatt" id="formInput#text" type="password" name="password2"
                            placeholder="Повторите пароль" />
                    </div>

                    <button class="save" type="submit">Сохранить</button>
                </form>
            </div>
        </container>
</body>
</html>

users/templates/users/createMes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/createMessage.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Inbox</title>
</head>
<body>
    <header>
        <a href="{% url 'projects' %}" class="logo">FOLIo</a>
            <a href="" class="text1">Для вас</a>
            <a href="" class="text2">Подписки</a>
            <a href="{% url 'inbox' %}" class="text3">Чаты</a>
            <a href="" class="text4">Вы сохранили</a>
            <a href="" class="text5">О нас</a>
            <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                <img class="profile" src="{{ profile.image.url }}" alt="profile">
            <nav class="menu" id="menu">
                <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                <a href="{% url 'account' %}">Профиль</a>
                <a href="{% url 'logout' %}">Выход</a>
            </nav>
            <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
            <script src="{% static 'js/mainPage.js' %}"></script>
    </header>
        <container>
            <div class="post-logo">
                <div class="post-logo">
                    <img class="post-logo-img" src="{% static 'img/изображение 10.png' %}" alt="post-logo-img">
                    <p class="post-logo-text">Общайся вместе с FOLIo</p>
                </div>
            </div>
        </container>
        <container>
            <div class="background"></div>
            <button class="w-btn1" href="">Новые(<span>{{unreadCount}}</span>)</button>
            <button class="w-btn2" href="">Все входящие</button>
            <button class="w-btn3" href="">Избранные</button>
            <button class="w-btn4" href="">Отправленные</button>
            <div class="block"></div>

        </container>

        <img class="chat-ava" src="{{ profile.image.url }}" alt="profile">

        <form class="form" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{ form.name.label }}</label>
                    {{ form.name }}
                </div>

                <div class="form__field">
                    <label for="formInput#text">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
                {% endif %}

                <div class="chat-block1">
                    <input class="chat-block11" id="id_subject" type="text" name="subject"
                                placeholder="Тема..."/>
                </div>

                <div class="chat-block2">
                    <input class="chat-block22" id="id_body" type="text" name="body"
                                placeholder="Описание..."/>
                </div>

                <input class="bitn" type="submit" value="Отправить" />
        </form>

</body>
</html>

users/templates/users/inbox.html
{% extends 'base.html' %}

{% block content %}
<main class="inbox my-xl">
  <div class="content-box">
    <h3 class="inbox__title">Новые сообщения:(<span>{{unreadCount}}</span>)</h3>

    <ul class="messages">
      {% for message in messageRequests %}
      {% if message.is_read == False %}
      <li class="message message--unread">
        {% else %}
      <li class="message">
        {% endif %}

        <a href="{% url 'message' message.id %}">
          <span class="message__author">{{message.name}}</span>
          <span class="message__subject">{{message.subject}}</span>
          <span class="message__date">{{message.created}}</span>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</main>

{% endblock content %}

users/templates/users/login.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Авторизация</title>
</head>
<body>

    <div class="notebook"><img src="{% static 'img/ноутбук.png' %}" alt=""></div>
    <div class="screen"><img src="{% static 'img/главэкран.png' %}" alt=""></div>

    <section>
        <div class="login"></div>
        <div class="text">Вход в систему</div>
         <form action="" method="POST">
            {% csrf_token %}

            <div class="log1">
                <label for="formInput#text"></label>
                <input class="p1" id="formInput#text" type="text" name="username"
                    placeholder="Логин" />
            </div>
            <div class="log2">
                <label for="formInput#password"></label>
                  <input class="p2" id="formInput#passowrd" type="password" name="password"
                    placeholder="Пароль" />
            </div>

            <button class="button" type="submit">Войти</button>
         </form>

            <div class="line"></div>
            <div class="comment1">Забыли пароль?</div>
            <div class="comment2">Нет аккаунта? <a href="{% url 'register' %}">Зарегистрироваться</a></div>
    </section>

</body>


</html>

{% endblock content %}

users/templates/users/mess.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/mess.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Message</title>
</head>
<body>
    <header>
        <a href="{% url 'projects' %}" class="logo">FOLIo</a>
            <a href="" class="text1">Для вас</a>
            <a href="" class="text2">Подписки</a>
            <a href="{% url 'inbox' %}" class="text3">Чаты</a>
            <a href="" class="text4">Вы сохранили</a>
            <a href="" class="text5">О нас</a>
            <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                <img class="profile" src="{{ profile.image.url }}" alt="profile">
            <nav class="menu" id="menu">
                <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                <a href="{% url 'account' %}">Профиль</a>
                <a href="{% url 'logout' %}">Выход</a>
            </nav>
            <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
            <script src="{% static 'js/mainPage.js' %}"></script>
    </header>
        <container>
            <div class="post-logo">
                <div class="post-logo">
                    <img class="post-logo-img" src="{% static 'img/изображение 10.png' %}" alt="post-logo-img">
                    <p class="post-logo-text">Общайся вместе с FOLIo</p>
                </div>
            </div>
        </container>
        <container>
            <div class="background"></div>
            <button class="w-btn1" href="">Новые</button>
            <button class="w-btn2" href="">Все входящие</button>
            <button class="w-btn3" href="">Избранные</button>
            <button class="w-btn4" href="">Отправленные</button>
            <div class="block"></div>
            <a href="{% url 'user-profile' message.sender.username  %}" class="chat-block">{{ message.name }}</a>
            <img class="chat-ava" src="{{ message.sender.image.url }}" alt="profile">
            <div class="chat-block1">{{ message.created }}</div>
            <div class="chat-block2">{{ message.body|linebreaksbr }}</div>
        </container>
</body>
</html>

users/templates/users/message.html
{% extends 'base.html' %}


{% block content %}
<main class="messagePage my-xl">
  <div class="content-box">
    <div class="message">
      <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
      <h4 class="message__subject">{{ message.subject }}</h4>
        {% if message.sender %}
        <a href="{% url 'user-profile' message.sender.username  %}" class="message__author">{{ message.name }}</a>
        {% else %}
        <p class="message__author">{{ message.name }}</p>
        {% endif %}
        <p class="message__date">{{ message.created }}</p>
        <div class="message__body">{{ message.body|linebreaksbr }}</div>
    </div>
  </div>
</main>
{% endblock content %}