itfinder/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('projects.urls')),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.projects, name="projects"),
    path('project/<slug:project_slug>/', views.project, name="project"),
    path('tag/<slug:tag_slug>', views.projects_by_tag, name="tag"),
    path('create-project/', views.createProject, name="create-project"),
    path('update-project/<str:pk>', views.updateProject, name="update-project"),
    path('delete-project/<str:pk>', views.deleteProject, name="delete-project"),
]

users/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('profiles/', views.profiles, name="profiles"),
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),   
    path('profile/<str:username>/', views.userProfile, name="user-profile"),
    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editAccount, name="edit-account"),
    path('create-skill/', views.createSkill, name="create-skill"),
    path('update-skill/<slug:skill_slug>/', views.updateSkill, name="update-skill"),
    path('delete-skill/<slug:skill_slug>/', views.deleteSkill, name="delete-skill"),
    path('skill/<slug:skill_slug>', views.profiles_by_skill, name="skill"),
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:username>/', views.createMessage, name="create-message"),

]

projects/models.py
from django.db import models
from users.models import Profile
import uuid
from django.utils.text import slugify

class Tag(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name    


class Project(models.Model):
    owner = models.ForeignKey(
        Profile, null=True, blank=True, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    image = models.ImageField(null=True, blank=True, default="project_images/default.jpg", upload_to='project_images')
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField(Tag, blank=True)
    total_votes = models.IntegerField(default=0, null=True, blank=True)
    votes_ratio = models.IntegerField(default=0, null=True, blank=True)
    demo_link = models.CharField(max_length=500, null=True, blank=True)
    source_link = models.CharField(max_length=500, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()
        queryset = self.review_set.all().values_list('owner__id', flat=True).count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = upVotes
        self.vote_ratio = queryset

        self.save()

    class Meta:
        ordering = ('-created',)


class Review(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        unique_together = [['owner', 'project']]
        ordering = ('created', )

    def __str__(self):
        return self.body


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    liked_object = models.ForeignKey(Project, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'liked_object')

projects/forms.py
from django.forms import ModelForm
from django import forms
from .models import Project, Review


class ProjectForm(ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'slug', 'image', 'tags', 'description', 'demo_link', 'source_link']
        labels = {
            'title': 'Название проекта',
            'slug': 'Слаг',
            'image':'Скриншот проекта',
            'tags':'Теги', 
            'description':'Описание проекта',
            'demo_link':'Демо-версия',
            'source_link':'Исходный код на GitHub'
        }

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        super(ProjectForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})    


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['body']

projects/views.py
import datetime
import time

from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Tag, Review, Like
from .forms import ProjectForm, ReviewForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import paginator
from .utils import paginateProjects, searchProjects


def projects(request):
    projects, search_query = searchProjects(request)
    reviewCount = Review.objects.all()

    if request.user.is_authenticated:
        profile = request.user.profile

        context = {'projects': projects, 'search_query': search_query, 'profile': profile, 'review': reviewCount}
        return render(request, 'projects/glavnaya.html', context)

    context = {'projects': projects, 'search_query': search_query, 'review': reviewCount}
    return render(request, 'projects/glavnaya.html', context)


def like(request, pk):
    obj = get_object_or_404(Project, pk=pk)
    like, created = Like.objects.get_or_create(user=request.user, liked_object=obj)

    if not created:
        like.delete()

    return redirect('projects')


def project(request, project_slug):
    project = Project.objects.get(slug=project_slug)
    tags = project.tags.all()
    form = ReviewForm()
    comments = project.reviewers.all()

    if request.user.is_authenticated:
        profile = request.user.profile

        if request.method == 'POST':
            form = ReviewForm(data=request.POST)

            if form.is_valid():
                review = form.save(commit=False)
                review.project = project
                review.owner = request.user.profile
                review.save()

        else:
            form = ReviewForm()

        return render(request, 'projects/singleProj.html', {'project': project, 'form': form, 'profile': profile, 'comments': comments})

    return render(request, 'projects/singleProj.html', {'project': project, 'form': form, 'comments': comments})


@login_required(login_url="login")
def createProject(request):
    profile = request.user.profile
    form = ProjectForm()

    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',',  " ").split()
        form = ProjectForm(request.POST, request.FILES)
        if form.is_valid():
            project = form.save(commit=False)
            project.owner = profile
            project.save()

            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)
            return redirect('account')

    context = {'form': form, 'profile': profile}
    return render(request, "projects/proj_form.html", context)


@login_required(login_url="login")
def updateProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    form = ProjectForm(instance=project)

    if request.method == 'POST':
        newtags = request.POST.get('newtags').replace(',',  " ").split()

        form = ProjectForm(request.POST, request.FILES, instance=project)
        if form.is_valid():
            project = form.save()
            for tag in newtags:
                tag, created = Tag.objects.get_or_create(name=tag)
                project.tags.add(tag)

            return redirect('account')

    context = {'form': form, 'project': project, 'profile': profile}
    return render(request, "projects/proj_form.html", context)


@login_required(login_url="login")
def deleteProject(request, pk):
    profile = request.user.profile
    project = profile.project_set.get(id=pk)
    if request.method == 'POST':
        project.delete()
        return redirect('account')
    context = {'object': project}
    return render(request, 'delete_template.html', context)


def projects_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    projects = Project.objects.filter(tags__in=[tag])
    context = {
        "projects": projects
    }

    return render(request, "projects/glavnaya.html", context)

projects/templates/projects/glavnaya.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/home.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Home</title>
</head>
<body>
    <header>
        <div class="logo">FOLIo</div>
        <div class="search">
            <div class="form-input">
                <form id='searchForm' action="{% url 'projects' %}" class="form-search" method="get">
                   <input type="text" class="input-search-1" placeholder="Поиск" id="formInput#search" name="search_query"
                   value="{{ search_query }}">
                   <button class="button-img">
                    <img src="{% static 'img/пупа.png' %}" alt="search" >
                   </button>
            {% if request.user.is_authenticated %}
                <a href="" class="text1">Для вас</a>
                <a href="" class="text2">Подписки</a>
                <a href="{% url 'inbox' %}" class="text3">Чаты</a>
                <a href="" class="text4">Вы сохранили</a>
                <a href="" class="text5">О нас</a>
                <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                    <img class="profile" src="{{ profile.image.url }}" alt="profile">
                <nav class="menu" id="menu">
                    <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                    <a href="{% url 'account' %}">Профиль</a>
                    <a href="{% url 'logout' %}">Выход</a>
                </nav>
                <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
                <script src="{% static 'js/mainPage.js' %}"></script>
            {% else %}
                   <a href="{% url 'login' %}" class="text4">Войти</a>
                    <a href="{% url 'register' %}" class="text5">Зарегистрироваться</a>
            {% endif %}
    </header>
        <container>
            <div class="post-logo">
                <img class="post-logo-img" src="{% static 'img/изображение 4.png' %}" alt="post-logo-img">
                <p class="post-logo-text">Создавай и делись вместе с FOLIo</p>
            </div>
        </container>

    <section>
        {% for project in projects %}
            <div class="block">
                <div class="block-panel">
                    <div class="title">{{ project.title }}</div>
                </div>
                <a href="{% url 'project' project.slug %}" class="project">
                    <img class="block-inpanel" src="{{ project.image.url }}" alt="скриншот проекта"/>
                </a>
                <a href="{% url 'user-profile' project.owner %}">
                    <img class="avatar" src="{{ project.owner.image.url }}" alt="image" />
                </a>
                <p><a class="nickname" href="{% url 'user-profile' project.owner %}">{{ project.owner.name }}</a></p>
                <img class="heart" src="{% static 'img/Union.png' %}">
                <img class="comment" src="{% static 'img/Group 2.png' %}">
                <p class="like">{{ project.total_votes }}</p>
                <p class="comm">{{ project.reviewers.count }}</p>
                {% for tag in project.tags.all %}
                    <div class="tegs">{{ tag }}</div>
                {% endfor %}
            </div>
        {% endfor %}
    </section>
<div>
</body>
{% include 'pagination.html' with queryset=projects custom_range=custom_range %}
</html>

projects/templates/projects/proj_form.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/editProj.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Edit Project</title>
</head>
<body>
    <header>
        <a href="{% url 'projects' %}" class="logo">FOLIo</a>
            <a href="" class="text1">Для вас</a>
            <a href="" class="text2">Подписки</a>
            <a href="{% url 'inbox' %}" class="text3">Чаты</a>
            <a href="" class="text4">Вы сохранили</a>
            <a href="" class="text5">О нас</a>
            <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                <img class="profile" src="{{ profile.image.url }}" alt="profile">
            <nav class="menu" id="menu">
                <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                <a href="{% url 'account' %}">Профиль</a>
                <a href="{% url 'logout' %}">Выход</a>
            </nav>
            <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
            <script src="{% static 'js/mainPage.js' %}"></script>
    </header>
        <container>
            <div class="post-logo">
                <img class="post-logo-img" src="{% static 'img/изображение 10.png' %}" alt="post-logo-img">
            </div>
        </container>
        <container>

                <div class="block-prof">
                    <form class="form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}

                        <div class="name">Теги</div>

                        <div class="town">Скриншот проекта</div>

                        <div class="opisanie">
                            <input class="opisaniee" id="id_title" type="text" name="title"
                                placeholder="Название проекта" value="{{ project.title }}"/>
                        </div>

                        <div class="vdohnovenie">
                            <input class="vdohnoveniee" id="id_slug" type="text" name="slug"
                                placeholder="Слаг" value="{{ project.slug }}"/>
                        </div>

                        <div class="achizment">
                            <input class="achizmentt" id="id_description" type="text" name="description"
                                placeholder="Описание" value="{{ project.description }}"/>
                        </div>

                        <div class="github">
                            <input class="githubb" id="id_source_link" type="text" name="source_link"
                                placeholder="Проект на GitHub" value="{{ project.source_link }}"/>
                        </div>

                        <div class="password">
                            <label for="formInput#text"></label>
                            <input class="passwordd" type="text" name="newtags" placeholder="Добавьте собственные теги">
                        </div>

                        <div class="repeat">
                            <img class="repeatt" src="{{ project.image.url }}">
                            <input class="input__file" type="file" name="image" accept="image/*" multiple>
                        </div>

                        <button class="save" type="submit">Опубликовать</button>
                    </form>
                </div>

        </container>
</body>
</html>

projects/templates/projects/singleProj.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/projectPage.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu+Mono&display=swap" rel="stylesheet">
    <title>Project Page</title>
</head>
<body>
    <header>
        <a href="{% url 'projects' %}" class="logo">FOLIo</a>
            {% if request.user.is_authenticated %}
                <a href="" class="text1">Для вас</a>
                <a href="" class="text2">Подписки</a>
                <a href="{% url 'inbox' %}" class="text3">Чаты</a>
                <a href="" class="text4">Вы сохранили</a>
                <a href="" class="text5">О нас</a>
                <img class="around" src="{% static 'img/Ellipse 4.png' %}" alt="around">
                    <img class="profile" src="{{ profile.image.url }}" alt="profile">
                <nav class="menu" id="menu">
                    <a class="close" href="javascript:void(0)" onclick="closeMenu()">&#10006;</a>
                    <a href="{% url 'account' %}">Профиль</a>
                    <a href="{% url 'logout' %}">Выход</a>
                </nav>
                <span onclick="openMenu()"><img class="arrow" src="{% static 'img/стрелка.png' %}" alt="arrow"></span>
                <script src="{% static 'js/mainPage.js' %}"></script>
            {% else %}
                   <a href="{% url 'login' %}" class="text4">Войти</a>
                    <a href="{% url 'register' %}" class="text5">Зарегистрироваться</a>
            {% endif %}
    </header>
        <container>
            <div class="post-logo">
                <img class="post-logo-img" src="{% static 'img/изображение 10.png' %}" alt="post-logo-img">
            </div>
        </container>

    <container>
        <div class="avatar">
            <img class="avatarr" src="{{ project.owner.image.url }}" alt="profile">
        </div>
        <p class="nickname">{{ project.owner.name }}</p>
        <h1 class="post-name">{{ project.title }}</h1>
        <img class="img-block" src="{{ project.image.url }}">
        <div class="text-block">{{ project.description }}</div>
        {% for tag in project.tags.all %}
            <div class="tegss">{{ tag }}</div>
        {% endfor %}
        <div class="slk">
            <a class="singleProject__liveLink" href="{{ project.source_link }}" target="_blank"><i
                        class="im im-external-link"></i>Исходный код на GitHub
            </a>
        </div>
        <div class="block-comments">Комментарии</div>

        <div class="comment">
            <div class="comments">
                {% for review in project.review_set.all %}

                    <div class="chat">
                        <p class="chatt">{{ review.body }}</p>
                    </div>
                    <div class="avatar-chat">
                        <a href="{% url 'user-profile' review.owner  %}">
                            <img class="avatar-chatt" src="{{ review.owner.image.url }}" alt="user" />
                        </a>
                    </div>

                {% endfor %}
            </div>

            <div class="dialog-block">

                {% if request.user.profile.id in project.reviewers %}
                    <p>Вы уже писали отзыв об этом проекте</p>

                {% elif request.user.profile == project.owner %}
                    <p>Вы не можете оставлять отзывы к собственным проектам</p>

                {% elif request.user.is_authenticated %}
                    <form action="." method="POST">
                        {% csrf_token %}

                            <input class="dialog-blockk" id="id_body" type="text" name="body"
                                    placeholder="Написать комментарий..."/>

                        <button class="save" type="submit">Добавить отзыв</button>
                    </form>

                {% else %}
                    <a href="{% url 'login' %}?next={{ request.path }}">Войдите, чтобы оставить отзыв</a>
                {% endif %}
            </div>
        </div>

    </container>
</body>
</html>